/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef __LSR_HFI_IO_H__
#define __LSR_HFI_IO_H__

#include <linux/io.h>

#define CVP_TOP_BASE_OFFS			0x00000000
#define LSR0_SS_IDLE_STATUS		(CVP_TOP_BASE_OFFS + CVP_LSR0_TOP_CVP + 0x2C)
#define LSR1_SS_IDLE_STATUS		(CVP_TOP_BASE_OFFS + CVP_LSR1_TOP_CVP + 0x2C)

#define CVP_LSR0_TOP_CVP			0x00034000
#define CVP_LSR1_TOP_CVP			0x00054000

#define LSR_CPU_BASE_OFFS			0x000A0000
#define LSR_AON_BASE_OFFS			0x000E0000

#define LSR_CPU_CS_A2HSOFTINTEN		(LSR_CPU_BASE_OFFS + 0x10)
#define LSR_CPU_CS_A2HSOFTINTENCLR	(LSR_CPU_BASE_OFFS + 0x14)
#define LSR_CPU_CS_A2HSOFTINT		(LSR_CPU_BASE_OFFS + 0x18)
#define LSR_CPU_CS_A2HSOFTINTCLR	(LSR_CPU_BASE_OFFS + 0x1C)
#define LSR_CPU_CS_VMIMSG		(LSR_CPU_BASE_OFFS + 0x34)
#define LSR_CPU_CS_VMIMSGAG0		(LSR_CPU_BASE_OFFS + 0x38)
#define LSR_CPU_CS_VMIMSGAG1		(LSR_CPU_BASE_OFFS + 0x3C)
#define LSR_CPU_CS_VMIMSGAG2		(LSR_CPU_BASE_OFFS + 0x40)
#define LSR_CPU_CS_VMIMSGAG3		(LSR_CPU_BASE_OFFS + 0x44)
#define LSR_CPU_CS_SCIACMD			(LSR_CPU_BASE_OFFS + 0x48)
#define LSR_CPU_CS_AXI4_QOS		(LSR_CPU_BASE_OFFS + 0x13C)
#define LSR_CPU_CS_H2XSOFTINTEN		(LSR_CPU_BASE_OFFS + 0x148)

/* LSR_CTRL_STATUS */
#define LSR_CPU_CS_SCIACMDARG0		(LSR_CPU_BASE_OFFS + 0x4C)
#define LSR_CPU_CS_SCIACMDARG0_BMSK	0xff
#define LSR_CPU_CS_SCIACMDARG0_SHFT	0x0
#define LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK	0xfe
#define LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_SHFT	0x1
#define LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_BMSK	0x1
#define LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_SHFT	0x0
#define LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY           0x100

/* HFI_QTBL_INFO */
#define LSR_CPU_CS_SCIACMDARG1		(LSR_CPU_BASE_OFFS + 0x50)

/* HFI_QTBL_ADDR */
#define LSR_CPU_CS_SCIACMDARG2		(LSR_CPU_BASE_OFFS + 0x54)

/* HFI_VERSION_INFO */
#define LSR_CPU_CS_SCIACMDARG3		(LSR_CPU_BASE_OFFS + 0x58)

/* LSR_SFR_ADDR */
#define LSR_CPU_CS_SCIBCMD		(LSR_CPU_BASE_OFFS + 0x5C)

/* CVP_MMAP_ADDR */
#define LSR_CPU_CS_SCIBCMDARG0		(LSR_CPU_BASE_OFFS + 0x60)

/* LSR_UC_REGION_ADDR */
#define LSR_CPU_CS_SCIBARG1		(LSR_CPU_BASE_OFFS + 0x64)

/* LSR_UC_REGION_ADDR */
#define LSR_CPU_CS_SCIBARG2		(LSR_CPU_BASE_OFFS + 0x68)

#define LSR_CPU_CS_SCIBARG3		(LSR_CPU_BASE_OFFS + 0x6C)

#define LSR_CPU_CS_H2ASOFTINTEN		(LSR_CPU_BASE_OFFS + 0x148)
#define LSR_CPU_CS_H2ASOFTINTENCLR	(LSR_CPU_BASE_OFFS + 0x14c)
#define LSR_CPU_CS_H2ASOFTINT		(LSR_CPU_BASE_OFFS + 0x150)
#define LSR_CPU_CS_H2ASOFTINTCLR	(LSR_CPU_BASE_OFFS + 0x154)

#define CVP_AHB_BRIDGE_SYNC_RESET	(LSR_CPU_BASE_OFFS + 0x160)

/* FAL10 Feature Control */
#define LSR_CPU_CS_X2RPMh		(LSR_CPU_BASE_OFFS + 0x168)
#define LSR_CPU_CS_X2RPMh_MASK0_BMSK	0x1
#define LSR_CPU_CS_X2RPMh_MASK0_SHFT	0x0
#define LSR_CPU_CS_X2RPMh_MASK1_BMSK	0x2
#define LSR_CPU_CS_X2RPMh_MASK1_SHFT	0x1
#define LSR_CPU_CS_X2RPMh_SWOVERRIDE_BMSK	0x4
#define LSR_CPU_CS_X2RPMh_SWOVERRIDE_SHFT	0x3

#define LSR_CPU_CS_X2RPMh_STATUS	(LSR_CPU_BASE_OFFS + 0x170)

/*
 * --------------------------------------------------------------------------
 * MODULE: lsr_wrapper
 * --------------------------------------------------------------------------
 */
#define LSR_WRAPPER_BASE_OFFS		0x000B0000

#define LSR_WRAPPER_HW_VERSION		(LSR_WRAPPER_BASE_OFFS + 0x00)
#define LSR_WRAPPER_HW_VERSION_MAJOR_VERSION_MASK  0x78000000
#define LSR_WRAPPER_HW_VERSION_MAJOR_VERSION_SHIFT 28
#define LSR_WRAPPER_HW_VERSION_MINOR_VERSION_MASK  0xFFF0000
#define LSR_WRAPPER_HW_VERSION_MINOR_VERSION_SHIFT 16
#define LSR_WRAPPER_HW_VERSION_STEP_VERSION_MASK   0xFFFF

#define LSR_WRAPPER_INTR_STATUS	(LSR_WRAPPER_BASE_OFFS + 0x0C)
#define LSR_WRAPPER_INTR_STATUS_A2HWD_BMSK	0x8
#define LSR_WRAPPER_INTR_STATUS_A2H_BMSK	0x4

#define CVP_SS_IRQ_MASK    (CVP_TOP_BASE_OFFS + 0x04)
#define CVP_SS_INTR_BMASK  (0x100)
#define LSR_WRAPPER_INTR_MASK		(LSR_WRAPPER_BASE_OFFS + 0x10)
#define CVP_FATAL_INTR_BMSK	(LSR_WRAPPER_INTR_MASK_CPU_NOC_BMSK | \
				LSR_WRAPPER_INTR_MASK_CORE_NOC_BMSK)
#define LSR_WRAPPER_INTR_MASK_CPU_NOC_BMSK	0x40
#define LSR_WRAPPER_INTR_MASK_CORE_NOC_BMSK	0x20
#define LSR_WRAPPER_INTR_MASK_A2HWD_BMSK	0x8
#define LSR_WRAPPER_INTR_MASK_A2HCPU_BMSK	0x4
#define LSR_WRAPPER_INTR_MASK_A2HCPU_SHFT	0x2

#define LSR_WRAPPER_INTR_CLEAR		(LSR_WRAPPER_BASE_OFFS + 0x14)

#define LSR_WRAPPER_TZ_BASE_OFFS		0x000C0000

#define LSR_WRAPPER_TZ_CPU_CLOCK_CONFIG	(LSR_WRAPPER_TZ_BASE_OFFS)
#define LSR_WRAPPER_INTR_CLEAR_A2HWD_BMSK	0x10
#define LSR_WRAPPER_INTR_CLEAR_A2HWD_SHFT	0x4
#define LSR_WRAPPER_INTR_CLEAR_A2H_BMSK	0x4
#define LSR_WRAPPER_INTR_CLEAR_A2H_SHFT	0x2
#define LSR_WRAPPER_CPU_STATUS		(LSR_WRAPPER_TZ_BASE_OFFS + 0x10)
#define LSR_WRAPPER_AXI_CLOCK_CONFIG	(LSR_WRAPPER_TZ_BASE_OFFS + 0x14)
#define LSR_WRAPPER_QNS4PDXFIFO_RESET	(LSR_WRAPPER_TZ_BASE_OFFS + 0x18)
#define LSR_WRAPPER_CPU_CGC_DIS	(LSR_WRAPPER_BASE_OFFS + 0x2010)

#define LSR_WRAPPER_CPU_CLOCK_CONFIG	(LSR_WRAPPER_BASE_OFFS + 0x50)
#define LSR_WRAPPER_DEBUG_BRIDGE_LPI_CONTROL	(LSR_WRAPPER_BASE_OFFS + 0x54)
#define LSR_WRAPPER_DEBUG_BRIDGE_LPI_STATUS	(LSR_WRAPPER_BASE_OFFS + 0x58)
#define LSR_WRAPPER_CPU_NOC_LPI_CONTROL		(LSR_WRAPPER_BASE_OFFS + 0x5C)
#define LSR_WRAPPER_CPU_NOC_LPI_STATUS		(LSR_WRAPPER_BASE_OFFS + 0x60)
#define LSR_WRAPPER_CORE_CLOCK_CONFIG		(LSR_WRAPPER_BASE_OFFS + 0x88)
#define LSR_WRAPPER_CORE_SW_RESET_TRIGGER		(LSR_WRAPPER_BASE_OFFS + 0x94)
#define LSR_WRAPPER_CORE_SW_RESET_H		(LSR_WRAPPER_BASE_OFFS + 0x98)
#define LSR_WRAPPER_CORE_SW_RESET_L		(LSR_WRAPPER_BASE_OFFS + 0x9C)

#define LSR_CTRL_INIT		LSR_CPU_CS_SCIACMD

#define LSR_CTRL_STATUS	LSR_CPU_CS_SCIACMDARG0
#define LSR_CTRL_INIT_STATUS__M \
		LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_STATUS_BMSK
#define LSR_CTRL_ERROR_STATUS__M \
		LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_ERROR_STATUS_BMSK
#define LSR_CTRL_INIT_IDLE_MSG_BMSK \
		LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_INIT_IDLE_MSG_BMSK
#define LSR_CTRL_STATUS_PC_READY \
		LSR_CPU_CS_SCIACMDARG0_HFI_CTRL_PC_READY


#define LSR_QTBL_INFO		LSR_CPU_CS_SCIACMDARG1

#define LSR_QTBL_ADDR		LSR_CPU_CS_SCIACMDARG2

#define CVP_VERSION_INFO	LSR_CPU_CS_SCIACMDARG3

#define LSR_SFR_ADDR		LSR_CPU_CS_SCIBCMD
#define CVP_MMAP_ADDR		LSR_CPU_CS_SCIBCMDARG0
#define LSR_UC_REGION_ADDR	LSR_CPU_CS_SCIBARG1
#define LSR_UC_REGION_SIZE	LSR_CPU_CS_SCIBARG2

#ifdef CONFIG_LSR_SERAPH
 /*
  * --------------------------------------------------------------------------
  * MODULE: lsr_wrapper_xtss
  * --------------------------------------------------------------------------
  */
#define LSR_WRAPPER_XTS_OFFS		0x000C0000
#define LSR_WRAPPER_XTSS_SW_RESET_RO	(LSR_WRAPPER_XTS_OFFS + 0x20)
#endif
/*
 * --------------------------------------------------------------------------
 * MODULE: vcodec noc error log registers
 * --------------------------------------------------------------------------
 */
#define CVP_NOC_BASE_OFFS		0x000D0000

#define CVP_NOC_ERR_MAINCTL_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x8)
#define CVP_NOC_ERR_ERRCLR_LOW_OFFS	(CVP_NOC_BASE_OFFS + 0x18)

#define CVP_NOC_SBM_FAULTINEN0_LOW      (CVP_NOC_BASE_OFFS + 0x240)
#define CVP_NOC_SBM_FAULTINSTATUS0_LOW  (CVP_NOC_BASE_OFFS + 0x248)
#define CVP_NOC_SBM_SENSELN0_LOW	(CVP_NOC_BASE_OFFS + 0x300)

#define CVP_NOC_CORE_BASE_OFFS			0x00070000

#ifdef CONFIG_LSR_SERAPH

#define CVP_NOC_MAIN_SIDEBANDMANAGER_FAULTINEN0_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3040)

#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN0_LOW \
		(CVP_NOC_CORE_BASE_OFFS + 0x3100)
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN0_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x3104)
#define CVP_NOC_MAIN_SIDEBANDMANAGER_SENSELN1_HIGH \
		(CVP_NOC_CORE_BASE_OFFS + 0x310C)

#define CVP_NOC_CORE_ERR_MAINCTL_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x2008)
#define CVP_NOC_CORE_ERR_ERRCLR_LOW_OFFS \
		(CVP_NOC_CORE_BASE_OFFS + 0x2018)

#endif

/* AON_CVP_NOC_RESET */

#define CVP_NOC_RESET_REQ \
		(CVP_NOC_CORE_BASE_OFFS + 0xf000)
#define CVP_NOC_RESET_ACK \
		(CVP_NOC_CORE_BASE_OFFS + 0xf004)


#define LSR_AON_WRAPPER_CVP_NOC_LPI_CONTROL	(LSR_AON_BASE_OFFS + 0x8)
#define LSR_AON_WRAPPER_CVP_NOC_LPI_STATUS	(LSR_AON_BASE_OFFS + 0xC)
#define LSR_AON_WRAPPER_CVP_NOC_ARCG_CONTROL	(LSR_AON_BASE_OFFS + 0x14)
#define LSR_AON_WRAPPER_CVP_NOC_CORE_CLK_CONTROL	(LSR_AON_BASE_OFFS + 0x24)
#define LSR_AON_WRAPPER_CVP_NOC_CORE_SW_RESET	(LSR_AON_BASE_OFFS + 0x1C)
#define LSR_AON_WRAPPER_CVP_VIDEO_CTL_NOC_LPI_CONTROL	(LSR_AON_BASE_OFFS + 0x2C)
#define LSR_AON_WRAPPER_CVP_VIDEO_CTL_NOC_LPI_STATUS	(LSR_AON_BASE_OFFS + 0x30)
#define LSR_AON_WRAPPER_SPARE		(LSR_AON_BASE_OFFS + 0x28)

#define LSR_CC_BASE_OFFS			0xF8000

#ifdef CONFIG_LSR_SERAPH
#define LSR_CC_MVS0C_GDSCR			(LSR_CC_BASE_OFFS + 0x34)
#define LSR_CC_MVS0C_CBCR			(LSR_CC_BASE_OFFS + 0x64)
#define LSR_CC_MVS0_GDSCR			(LSR_CC_BASE_OFFS + 0x7C)
#define LSR_CC_MVS0_CBCR			(LSR_CC_BASE_OFFS + 0x90)
#define LSR_CC_AHB_CBCR				(LSR_CC_BASE_OFFS + 0xA4)
#define LSR_CC_XO_CBCR				(LSR_CC_BASE_OFFS + 0xD4)
#define LSR_CC_SLEEP_CBCR			(LSR_CC_BASE_OFFS + 0xF8)
#define LSR_CC_MVS0_FREERUN_CBCR		(LSR_CC_BASE_OFFS + 0xD8)
#define LSR_CC_MVS0C_FREERUN_CBCR		(LSR_CC_BASE_OFFS + 0xDC)
#define LSR_CC_SPARE1				(LSR_CC_BASE_OFFS + 0x1F24)
/*Added to debug HW Hang*/
#define GCC_LSR_AHB_CBCR			(0xA3004)
#define GCC_LSR_AXI0_CBCR			(0xA3008)
#define GCC_LSR_AXI0C_CBCR			(0xA301C)
#define GCC_LSR_XO_CBCR			(0xA3024)

#endif

#define CVP_LSR_L_NOC_BASE_OFFS      0x60000
#define CVP_LSR_R_NOC_BASE_OFFS      0x70000

#ifdef CONFIG_LSR_SERAPH
#define CVP_LSR_L_NOC_CSC_GCX_RD_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8030)
#define CVP_LSR_L_NOC_CSC_GCX_RD_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8034)
#define CVP_LSR_L_NOC_CSC_GCX_RD_NIU_URGENCY_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8038)
#define CVP_LSR_L_NOC_CSC_GCX_WR_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8230)
#define CVP_LSR_L_NOC_CSC_GCX_WR_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8234)
#define CVP_LSR_L_NOC_CSC_GCX_WR_NIU_URGENCY_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8238)
#define CVP_LSR_L_NOC_GCX_RD_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8430)
#define CVP_LSR_L_NOC_GCX_RD_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8434)
#define CVP_LSR_L_NOC_GCX_RD_NIU_URGENCY_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8438)
#define CVP_LSR_L_NOC_GCX_CSC_RD_128_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8630)
#define CVP_LSR_L_NOC_GCX_CSC_RD_128_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8634)
#define CVP_LSR_L_NOC_CACHE_GCX_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8830)
#define CVP_LSR_L_NOC_CACHE_GCX_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8834)
#define CVP_LSR_L_NOC_CACHE_GCX_NIU_URGENCY_LOW \
		(CVP_LSR_L_NOC_BASE_OFFS + 0X8838)

#define CVP_LSR_R_NOC_CSC_GCX_RD_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9030)
#define CVP_LSR_R_NOC_CSC_GCX_RD_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9034)
#define CVP_LSR_R_NOC_CSC_GCX_RD_NIU_URGENCY_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9038)
#define CVP_LSR_R_NOC_CSC_GCX_WR_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9230)
#define CVP_LSR_R_NOC_CSC_GCX_WR_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9234)
#define CVP_LSR_R_NOC_CSC_GCX_WR_NIU_URGENCY_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9238)
#define CVP_LSR_R_NOC_GCX_RD_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9430)
#define CVP_LSR_R_NOC_GCX_RD_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9434)
#define CVP_LSR_R_NOC_GCX_RD_NIU_URGENCY_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9438)
#define CVP_LSR_R_NOC_GCX_CSC_RD_128_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9630)
#define CVP_LSR_R_NOC_GCX_CSC_RD_128_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9634)
#define CVP_LSR_R_NOC_CACHE_GCX_NIU_PRIORITYLUT_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9830)
#define CVP_LSR_R_NOC_CACHE_GCX_NIU_PRIORITYLUT_HIGH \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9834)
#define CVP_LSR_R_NOC_CACHE_GCX_NIU_URGENCY_LOW \
		(CVP_LSR_R_NOC_BASE_OFFS + 0X9838)
#endif

#endif
