# SPDX-License-Identifier: GPL-2.0-only

KDIR := $(TOP)/kernel_platform/soc-repo

ifeq ($(CONFIG_ARCH_LAHAINA), y)
      include $(DISPLAY_ROOT)/config/gki_lahainadisp.conf
      LINUX_INC += -include $(DISPLAY_ROOT)/config/gki_lahainadispconf.h
endif

ifeq ($(CONFIG_ARCH_SM6150), y)
      include $(DISPLAY_ROOT)/config/sm6150disp.conf
      LINUX_INC += -include $(DISPLAY_ROOT)/config/sm6150dispconf.h
      subdir-ccflags-y += $(LE_EXTRA_CFLAGS)
endif

LINUX_INC += -I$(DISPLAY_ROOT)/../mm-drivers/msm_ext_display/include
ccflags-y += $(LINUX_INC)

obj-$(CONFIG_DRM_LT9611UXC) += lt9611uxc.o
obj-$(CONFIG_DRM_LONTIUM_LT9611) += lt9611.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
