# SPDX-License-Identifier: GPL-2.0-only

KDIR := $(TOP)/kernel_platform/msm-kernel

ifeq ($(CONFIG_ARCH_KALAMA), y)
	include $(DISPLAY_ROOT)/config/gki_kalamadisp.conf
	LINUX_INC += -include $(DISPLAY_ROOT)/config/gki_kalamadispconf.h
endif

obj-$(CONFIG_DRM_LT9611UXC) += lt9611uxc.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
